# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Encode-Unicode-Japanese
version:      0.02
version_from: lib/Encode/Unicode/Japanese.pm
installdirs:  site
requires:
    Test::More:                    0
    Unicode::Japanese:             0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
